### ISSUE TITLE
respect node.js modules

### ISSUE THREAD

**Issue by goatslacker** [coveraje/coveraje#11]
Currently it will set all vars as global and ignore any module.exports

**Comment by WolfgangKluge** [comment]
My mentioned big change include some improvements to node.js modules (includes require-support) - but can you please give me an example of what you mean exactly

**Comment by goatslacker** [comment]
Well for one things like require, module, process, etc don't work.

But besides that here's some code:

**coverage.js**

```
var foo = 1;
var bar = 2;
var baz = 3;

if (typeof module !== "undefined") {
  module.exports = bar;
}
```

**test.js**

```
var c = require('coveraje').coveraje;
var fs = require('fs');

c.cover(fs.readFileSync('./coverage.js').toString(), function (self) {
  console.log(self); // will contain self.foo, self.bar and self.baz when it should only use bar
}, {}, function () { console.log('done'); });
```

**Comment by WolfgangKluge** [comment]
Hm,...
first, there's an option `globals`. Set it to `node` and you can use require, module, process (it's not well tested and I don't think I have everything in yet, but the most important ones, see https://github.com/coveraje/coveraje/blob/master/lib/TestRunner.js#L73).

`self` is the "_global context_" of the script. This is intentional (not sure if it's good, but it's intentional *g*). With this you can e.g. access the variable `foo` inside the test function - so you don't have to rewrite your scripts and use `module.exports` (if not used yet).
But if you want to use `module.exports`, you can do it (by using node-globals) and accessing it with `self.module.exports`...

The **new** require (part of the change) is a possibility to also inspect the code loaded with `require`... Hope I can release it soon

**Comment by goatslacker** [comment]
Sweet, I'll close this since you have it in your plans already.
