### ISSUE TITLE
feature request: make instrumented code available through API

### ISSUE THREAD

**Issue by goatslacker** [coveraje/coveraje#15]

**Comment by WolfgangKluge** [comment]
It is available through `instance.getCodes()` (horrible name, I know... Maybe I should rename it).
But there's currently no property with the key used in Runtime.js (but such a property is coming soon).

`instance` is accessible inside onComplete-function (first parameter) `coveraje.cover(code, runner, options, onComplete)`. There's no sync version (yet), since the tests might be async, too.

If you want it for reports (like requested in #14), wait for this feature - I currently implement it and you can use your own formatters (should be much easier)..

**Comment by WolfgangKluge** [comment]
I've cherry picked some of the changes to master, so now you can access `index`-property of each file returned by `getCodes` (this index is used as key inside runtime)

**Comment by goatslacker** [comment]
getCode isn't a bad name. Should be singular though.

If you want to be more specific you can rename to getInstrumentedCode()

**Comment by goatslacker** [comment]
Oh, also -- I need it accessible inside runner.

**Comment by WolfgangKluge** [comment]
It's in master now. Second argument of every runner function is the coveraje instance... ;)
