### ISSUE TITLE
require doesn't work for relative paths

### ISSUE THREAD

**Issue by goatslacker** [coveraje/coveraje#24]
Simplest use case I could make:

`hi.js`

```
module.exports = 'hello';
```

`cover.js`

```
var coveraje = require('coveraje').coveraje;

coveraje.cover(
  "console.log('1'); var foo = require('./hi.js'); console.log('2');",
  function (context, inst) {
    console.log(context.module.exports);
  },
  { globals: "node", colorizeShell: false }
);
```

1 will be printed to console. 2 will never be printed because `hi.js` will throw.

```
undefined: Error: Cannot find module './hi.js'
```

This is because `context.require` is set to the original require on 
[TestRunner.js:78](https://github.com/coveraje/coveraje/blob/master/lib/TestRunner.js#L78)

This will lookup packages based on relative path, and the path is set incorrectly (it points to `node_modules/coveraje/`)

To fix this the dev would need to supply the path where the script is at. This will change the API a bit.

Suggestions:
- In `options` the dev can specify a `fileName` like so:
  
  { global: "node", colorizeShell: false, fileName: "/home/me/absolute_path/to/module/file.js" }
- The first parameter of `cover` should take the filename and do the file reading? This means if it's node do an fs.readFile and if it's a browser get contents via http request.
- Add another parameter to the `cover` function where the dev sets it to the filename or dirname of where the script is located.
- coveraje.setFilename('/blah/foo/bar/baz.js') ?

Afterwards it's just  a matter of using node's `path` to `resolve()` the path and make it into an absolute path before passing it to require. That part is easy, I've already done that.

I can provide pull request.

**Comment by WolfgangKluge** [comment]
As a quick workaround, use `resolveRequires:["*"]` as option. Seems like I always have to modify `require`...
Thanks for reporting.

**Comment by WolfgangKluge** [comment]
OK, found a solution - quite the same as you provided for `exports` ;)
`require` points now to `module.require`

**Comment by itay** [comment]
@WolfgangKluge just an FYI, I attempted to do this for Cover, but ended up giving up this approach because it just introduced too many issues. It breaks globals to some degree, and there are many weird edge cases.

**Comment by goatslacker** [comment]
@itay interesting. Can you share some of your experiences?

How does it break globals and what are some edge cases that you found?

**Comment by goatslacker** [comment]
I'm asking because I just [open-sourced an npm-module](https://github.com/goatslacker/dune) that handles scripts inside VMs

**Comment by WolfgangKluge** [comment]
Now it should be fixed.. Thanks again

@itay thanks. I'm very curious about the edge cases, too (and how it could break globals, since I try to do roughly the same as node.js - only with different paths and already loaded source code)..

**Comment by goatslacker** [comment]
I think it's still broken. Hang on.

**Comment by itay** [comment]
So here's what I saw, and I'm totally willing to believe that I just had a bug that I could not fix.

The way globals work in node by default is that they are shared across all modules. However, if you set the env variable NODE_MODULE_CONTEXTS to 1, then every module (i.e. every call to require) is done in a new context, and globals are no longer shared.

What I encountered in Cover is as soon as I executed something in a new context (vs in 'this' context) globals stopped being shared and were only 'global' for that module. Most times this is fine, but it broke things like Mocha (the testing framework).

They way Cover works is that it hooks into the require path such that on every require we will intercept it, instrument it and then let Node run the instrumented code. Originally, it would run every file in a context (the 'this' context, but still). I found that this ended up being very buggy, and basically meant I couldn't debug things. I also had trouble with getting the "main" module to work (as in, making a file thing it is the main module, and so believe it was run directly from the command line).

I recently changed it to work a bit differently (no more contexts), and it works much better since (and much more predictably). Anyway, let me know if you have any questions. Hopefully this was helpful

**Comment by goatslacker** [comment]
Ok I got it. I'll try and submit a failing test as a pull request.

**Comment by WolfgangKluge** [comment]
I'll revisit the design - maybe I get back to my first approach and try to load the code in it's own node process (would be the clearest solution)...

@goatslacker I don't know if this is a failing test or "only" a missing feature (but a needed one).
Currently, coveraje acts like the provided code is at the same location as the test file (so here it's the path to `require.js`).
What you are trying is to load code from a different location - this cannot work with relative paths (nowhere) - except with an extension like mentioned in your PR #28.
Or did I get something wrong?

**Comment by goatslacker** [comment]
This is meant to be a failing test for a missing feature.

It's TDD-style.

**Comment by goatslacker** [comment]
Assuming the covered code is in the same location as the test file is not practical. Usually the test file is in a `test/` directory while the code lives elsewhere.

**Comment by WolfgangKluge** [comment]
Right...
